package frsf.isi.died.tp.estructuras.contenido;

public enum TipoNodo {
	TITULO,METADATO,AUTOR,SECCION,PARRAFO,CAPITULO,EDITORIAL,RESUMEN,PALABRA_CLAVE,SITIO,EJERCICIO,FECHA_PUBLICACION,TITULOMETADATO,CAPITULOMETADATO
}
